---
- name: "Play 1: Configure Device"
  connection: network_cli
  hosts: routers
  tasks:
  - name: "Tasks 1: Config acl"
    cisco.ios.ios_acls:
      config:
      - afi: ipv4
        acls:
        - name: std_acl
          acl_type: standard
          aces:
          - grant: deny
            source:
              address: 192.168.1.200
          - grant: deny
            source:
              address: 192.168.2.0
              wildcard_bits: 0.0.0.255
    register: cli_result
  - name: "Task 2: Print results"
    debug:
      msg: "{{ cli_result }}"
  - name: "Task 3: save acl"
    cisco.ios.ios_config:
      save_when: modified
    
...
