---
- name: "Play 1: Get Device information"
  connection: network_cli
  hosts: routers
  tasks:
  - name: "Tasks 1: Get running config information"
    cisco.ios.ios_facts:
      gather_subset:
      - config
    register: cli_result
  - name: "Task 2: Print results"
    debug:
      msg: "{{ cli_result.ansible_facts.ansible_net_config }}"
  - name: "Task 3: create folder for backup config"
    file:
      path: "backups"
      state: directory
    run_once: true
  - name: "Task 4: Copy backups to backup directory"
    copy:
      content: "{{ cli_result.ansible_facts.ansible_net_config }}"
      dest: "backups/{{ inventory_hostname }}.txt"
...
