---
- name: "PLAY 1: Configure interfaces on router"
  hosts: 2250_wan_router
  connection: network_cli
  tasks:
    - name: "TASK 1: Configure Loopback interfaces via SSH/CLI"
      ios_config:
        src: "templates/loop_desc_int.j2"
        #save_when: changed
      notify: config_changed
      register: cli_result

  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result }}"
