---
Production:
  - ip: 10.102.30.30
    device_type: cisco_asa
    username: user
    password: pass
    secret: enable
  - ip: 10.102.30.251
    device_type: cisco_asa
    username: user
    password: pass
    secret: enable
