---
language: "python"
dist: "focal"
python:
  - "3.8.5"
services:
  - "docker"

install:
  - "cd meraki"
  - "pip install -r requirements.txt"

before_script:
  - "cd switch"
  - "cd warren_easton"
  - "python -m unittest test_update_portAccess.py"
  - "docker image build -t meraki_rest ."
  - "docker-compose up -d"
  - "docker container ls"

script:
  - "cd meraki"
  - "cd switch"
  - "cd warren_easton"
  - "python -m unittest test_update_portAccess.py"

after_script:
  - "docker-compose down"
...
