- name: Install web server (nginx on ubuntu)
  hosts: web
  become: yes # nick used true
  tasks:
  - name: "apt-get update"
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    ansible.builtin.apt:
      name: ['nginx']
      state: latest

  - name: "create www directory"
    ansible.builtin.file:
      path: /var/www/{{ domain }}/html
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: delete default nginx site
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    ansble.builtin.template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted