- name: update web server
  hosts: web
  tasks:
  - name: "sync website"
    synchronize:
      src: site/
      dest: /var/www/{{ domain }}/html
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no